name: assign2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  path: ^1.8.3
  pdf: ^3.10.4
  printing: ^5.12.0
  flutter_slidable: ^3.0.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
